### ISSUE TITLE
I'm not sure why the text in the Find/Replace fields are unbalanced

### ISSUE THREAD

**Issue by aubreypwd** [peaceant/gruvbox#1]
![](https://cloudup.com/cYbBR2zSOR9+?raw.png)

I've tried all kinds of settings, but this is xxs and compact, but no matter what setting I use the font doesn't seem to fit the inputs perfectly.

**Comment by peaceant** [comment]
This repo is only a gruvbox color scheme. No theme. I think you should raise an issue at https://github.com/Briles/gruvbox.

I would also (before raising an issue) try to resize (with a mouse) find and replace overlay window. That will usually fix a rendering of find and replace.
